-- AlterTable
ALTER TABLE "User" ADD COLUMN     "photoPositionX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "photoPositionY" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "photoZoom" DOUBLE PRECISION NOT NULL DEFAULT 1;

